from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'portaria'
urlpatterns = [
    path('', views.index, name='index'),
    path('portariaview/', views.Visualizacao.as_view(), name='visualizacao'),
    path('portaria/', views.cadastro, name='cadastro'),
    path('cadastro/cadastroentrada/', views.cadastroentrada, name='cadastroentrada'),
    path('cadastro/cadastrosaida/', views.cadastrosaida, name='cadastrosaida'),
    path('paletes/', views.paleteview, name='paleteview'),
    path('paletes/transfpaletes/', views.transfpalete, name='transfpaletes'),
    path('paletes/cadastro', views.cadpaletes, name='cadpaletes'),
    path('paletes/painelcliente', views.paletecliente, name='paletecliente'),
    path('paletes/saidapaletes', views.saidapalete, name='saidapalete'),
    path('frota/', views.frota, name='frota'),
    path('frota/<str:placa_id>&<moto_id>/checklist/', views.checklistfrota, name='checklistfrota'),
    path('frota/checklistview/', views.checklistview, name='checklistview'),
    path('frota/checklistview/<int:idckl>/detalhe', views.checklistdetail, name='checklistdetail'),
    path('frota/cadastros', views.frotacadastros, name='frotacadastros'),
    path('cadastros/motorista', views.cadmotorista, name='cadmotorista'),
    path('cadastros/veiculo', views.cadveiculo, name='cadveiculo'),
    path('cadastros/tipo_servico', views.cadtpservico, name='cadtpservico'),
    path('manutencao/', views.manutencaofrota, name='manutencaofrota'),
    path('manutencao/<str:placa_id>/entrada/', views.manuentrada, name='manuentrada'),
    path('manutencao/<int:osid>/saida/', views.manusaida, name='manusaida'),
    path('manutencao/view/', views.ManutencaoListView.as_view(), name='manutencaoview'),
    path('manutencao/<int:osid>/print', views.manutencaoprint, name='manutencaoprint'),
    path('manutencao/view/pendencia', views.manupendentes, name='manupendentes'),
    path('servicospj/', views.servicospj, name='servicospj'),
    path('servicospj/<int:args>/cadastro/', views.cadservicospj, name='cadservicospj'),
    path('servicospj/consulta/', views.consultanfpj, name='consultanfpj'),
    path('decimopj/', views.decimopj, name="decimopj"),
    path('decimopj/<int:idfunc>/parcela1', views.caddecimo1, name='caddecimo1'),
    path('decimopj/<int:idfunc>/parcela2', views.caddecimo2, name='caddecimo2'),
    path('decimopj/view', views.decimoview, name='decimoview'),
    path('feriaspj/', views.feriaspjv, name='feriaspjv'),
    path('feriaspj/cadastro', views.feriascad, name='feriascad'),
    path('feriaspj/view', views.feriasview, name='feriasview'),
    path('feriaspj/<int:idfpj>/agendamento', views.feriasagen, name='feriasagen'),
    path('feriaspj/<int:idfpj>/quitar', views.feriasquit, name='feriasquit'),
    path('cadastro-funcionariopj/', views.cadfuncionariopj, name='cadfuncionariopj'),
    path('atualizar-funcionariopj/', views.atualizarfunc, name='atualizarfunc'),
    path('fatferramentas/', views.fatferramentas, name='fatferramentas'),
    path('tickets/', views.monitticket, name='monitticket'),
    path('tickets/new/', views.tktcreate, name='tktcreate'),
    path('tickets/<tktid>/', views.closetkt, name='closetkt'),
    path('tickets/<tktid>/view/', views.tktview, name='tktview'),
    path('chamados/', views.chamado, name='chamado'),
    path('chamados/novo', views.chamadonovo, name='chamadonovo'),
    path('chamados/painel', views.chamadopainel, name='chamadopainel'),
    path('chamados/painel/<tktid>/detalhes', views.chamadodetail, name='chamadodetail'),
    path('chamados/chamadoreadmail', views.chamadoreadmail, name='chamadoreadmail'),
    path('replymail_monitoramento/<tktid>', views.replymail_monitoramento, name="replymail_monitoramento"),
    path(r'mailferias/<int:idfpj>', views.mailferias, name='mailferias'),
    path('outputs/', views.outputs, name='outputs'),
    path(r'edibuilder/', views.ediexceltosd1, name="ediexceltosd1"),
    path(r'ediexample/', views.exedicorreios, name="exedicorreios"),
    path(r'export-mail-nfpj/', views.get_nfpj_mail, name='get_nfpj_mail'),
    path(r'export-csv-nfpj/', views.get_nfpj_csv, name='get_nfpj_csv'),
    path(r'export-csv-port/', views.get_portaria_csv, name='get_portaria_csv'),
    path(r'export-csv-palete/', views.get_palete_csv, name='get_palete_csv'),
    path(r'export-csv-manu/', views.get_manu_csv, name='get_manu_csv'),
    path(r'export-13-pj/', views.get_pj13_mail, name='get_pj13_mail'),
    path(r'export-13-pj-csv/', views.get_pj13_csv, name='get_pj13_csv'),
    path(r'export-checklist-csv/', views.get_checklist_csv, name='get_checklist_csv'),
    path(r'export-ferias-csv/', views.get_ferias_csv, name='get_ferias_csv'),
    path(r'readmail/', views.readmail_monitoramento, name="readmail_monitoramento"),
    path('cardusuario/', views.cardusuario, name='cardusuario'),
    path('cardusuario/<int:id>/card', views.card, name='card'),
    path(r'readnotify/<notifyid>/', views.isnotifyread, name='isnotifyread'),
    path(r'allreadnotify/<user>', views.setallread, name='setallread'),
    path('testeconn/', views.testeconn, name='testeconn'),
    path(r'modaltkt/', views.modaltkt, name='modaltkt')

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)