# Generated by Django 3.2.6 on 2021-08-31 18:22

from django.db import migrations, models

from portaria.models import TIPO_MOT, TIPO_VIAGEM


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('placa2', models.CharField(max_length=20)),
                ('motorista', models.CharField(max_length=50)),
                ('empresa', models.IntegerField()),
                ('garagem', models.IntegerField()),
                ('tipo_func',  models.CharField(max_length=10, choices=TIPO_MOT)),
                ('tipo_viagem', models.CharField(max_length=10, choices=TIPO_VIAGEM)),
                ('hr_chegada', models.DateTimeField()),
                ('hr_saida', models.DateTimeField()),
            ],
        ),
    ]
