# Generated by Django 3.2.6 on 2021-09-13 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portaria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='filial',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='id',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='tipo_func',
            field=models.CharField(choices=[('INTERNO', 'INTERNO'), ('AGREGADO', 'AGREGADO')], default='INTERNO', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro',
            name='tipo_viagem',
            field=models.CharField(choices=[('COLETA', 'COLETA'), ('ENTREGA', 'ENTREGA')], default='COLETA', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='hr_chegada',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='hr_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='placa',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='placa2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
