# Generated by Django 3.2.6 on 2021-09-20 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='empresa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='hr_chegada',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='hr_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='placa',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='placa2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
