# Generated by Django 3.2.6 on 2021-09-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='placa',
            field=models.CharField(max_length=20, serialize=False),
        ),
    ]
