# Generated by Django 3.2.6 on 2023-01-06 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0002_auto_20230105_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ca',
            field=models.CharField(default=datetime.datetime(2023, 1, 6, 10, 45, 40, 232570), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bipagempalete',
            name='filial',
            field=models.CharField(choices=[('1', 'SPO'), ('2', 'REC'), ('3', 'SSA'), ('4', 'FOR'), ('5', 'MCZ'), ('6', 'NAT'), ('7', 'JPA'), ('8', 'AJU'), ('9', 'VDC'), ('10', 'CTG'), ('11', 'GVR'), ('12', 'VIX'), ('13', 'TCO'), ('14', 'UDI'), ('50', 'VIX'), ('20', 'SPO'), ('21', 'SPO'), ('20', 'CTG'), ('21', 'TCO'), ('22', 'UDI'), ('23', 'TMA'), ('24', 'VIX'), ('50', 'VIX'), ('30', 'BMA'), ('31', 'BPE'), ('32', 'BEL'), ('33', 'BPB'), ('34', 'SLZ'), ('35', 'BAL'), ('36', 'THE'), ('52', 'THE'), ('40', 'FMA'), ('0', 'MOV')], max_length=3),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='destino',
            field=models.CharField(blank=True, choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('CTG', 'CTG'), ('GVR', 'GVR'), ('VIX', 'VIX'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('BMA', 'BMA'), ('BPE', 'BPE'), ('BEL', 'BEL'), ('BPB', 'BPB'), ('SLZ', 'SLZ'), ('BAL', 'BAL'), ('THE', 'THE'), ('FMA', 'FMA'), ('MOV', 'MOV')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='origem',
            field=models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('CTG', 'CTG'), ('GVR', 'GVR'), ('VIX', 'VIX'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('BMA', 'BMA'), ('BPE', 'BPE'), ('BEL', 'BEL'), ('BPB', 'BPB'), ('SLZ', 'SLZ'), ('BAL', 'BAL'), ('THE', 'THE'), ('FMA', 'FMA'), ('MOV', 'MOV')], max_length=5),
        ),
        migrations.AlterField(
            model_name='estoquesolicitacoes',
            name='filial',
            field=models.CharField(choices=[('1', 'SPO'), ('2', 'REC'), ('3', 'SSA'), ('4', 'FOR'), ('5', 'MCZ'), ('6', 'NAT'), ('7', 'JPA'), ('8', 'AJU'), ('9', 'VDC'), ('10', 'CTG'), ('11', 'GVR'), ('12', 'VIX'), ('13', 'TCO'), ('14', 'UDI'), ('50', 'VIX'), ('20', 'SPO'), ('21', 'SPO'), ('20', 'CTG'), ('21', 'TCO'), ('22', 'UDI'), ('23', 'TMA'), ('24', 'VIX'), ('50', 'VIX'), ('30', 'BMA'), ('31', 'BPE'), ('32', 'BEL'), ('33', 'BPB'), ('34', 'SLZ'), ('35', 'BAL'), ('36', 'THE'), ('52', 'THE'), ('40', 'FMA'), ('0', 'MOV')], max_length=3),
        ),
        migrations.AlterField(
            model_name='etiquetasdocumento',
            name='garagem',
            field=models.CharField(choices=[('1', 'SPO'), ('2', 'REC'), ('3', 'SSA'), ('4', 'FOR'), ('5', 'MCZ'), ('6', 'NAT'), ('7', 'JPA'), ('8', 'AJU'), ('9', 'VDC'), ('10', 'CTG'), ('11', 'GVR'), ('12', 'VIX'), ('13', 'TCO'), ('14', 'UDI'), ('50', 'VIX'), ('20', 'SPO'), ('21', 'SPO'), ('20', 'CTG'), ('21', 'TCO'), ('22', 'UDI'), ('23', 'TMA'), ('24', 'VIX'), ('50', 'VIX'), ('30', 'BMA'), ('31', 'BPE'), ('32', 'BEL'), ('33', 'BPB'), ('34', 'SLZ'), ('35', 'BAL'), ('36', 'THE'), ('52', 'THE'), ('40', 'FMA'), ('0', 'MOV')], max_length=3),
        ),
        migrations.AlterField(
            model_name='etiquetaspalete',
            name='filial',
            field=models.CharField(choices=[('1', 'SPO'), ('2', 'REC'), ('3', 'SSA'), ('4', 'FOR'), ('5', 'MCZ'), ('6', 'NAT'), ('7', 'JPA'), ('8', 'AJU'), ('9', 'VDC'), ('10', 'CTG'), ('11', 'GVR'), ('12', 'VIX'), ('13', 'TCO'), ('14', 'UDI'), ('50', 'VIX'), ('20', 'SPO'), ('21', 'SPO'), ('20', 'CTG'), ('21', 'TCO'), ('22', 'UDI'), ('23', 'TMA'), ('24', 'VIX'), ('50', 'VIX'), ('30', 'BMA'), ('31', 'BPE'), ('32', 'BEL'), ('33', 'BPB'), ('34', 'SLZ'), ('35', 'BAL'), ('36', 'THE'), ('52', 'THE'), ('40', 'FMA'), ('0', 'MOV')], max_length=3),
        ),
        migrations.AlterField(
            model_name='funcpj',
            name='filial',
            field=models.CharField(blank=True, choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('CTG', 'CTG'), ('GVR', 'GVR'), ('VIX', 'VIX'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('BMA', 'BMA'), ('BPE', 'BPE'), ('BEL', 'BEL'), ('BPB', 'BPB'), ('SLZ', 'SLZ'), ('BAL', 'BAL'), ('THE', 'THE'), ('FMA', 'FMA'), ('MOV', 'MOV')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='validade',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='filial',
            field=models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('CTG', 'CTG'), ('GVR', 'GVR'), ('VIX', 'VIX'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('BMA', 'BMA'), ('BPE', 'BPE'), ('BEL', 'BEL'), ('BPB', 'BPB'), ('SLZ', 'SLZ'), ('BAL', 'BAL'), ('THE', 'THE'), ('FMA', 'FMA'), ('MOV', 'MOV')], max_length=3),
        ),
        migrations.AlterField(
            model_name='movpalete',
            name='destino',
            field=models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('CTG', 'CTG'), ('GVR', 'GVR'), ('VIX', 'VIX'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('BMA', 'BMA'), ('BPE', 'BPE'), ('BEL', 'BEL'), ('BPB', 'BPB'), ('SLZ', 'SLZ'), ('BAL', 'BAL'), ('THE', 'THE'), ('FMA', 'FMA'), ('MOV', 'MOV')], max_length=3),
        ),
        migrations.AlterField(
            model_name='movpalete',
            name='origem',
            field=models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('CTG', 'CTG'), ('GVR', 'GVR'), ('VIX', 'VIX'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('BMA', 'BMA'), ('BPE', 'BPE'), ('BEL', 'BEL'), ('BPB', 'BPB'), ('SLZ', 'SLZ'), ('BAL', 'BAL'), ('THE', 'THE'), ('FMA', 'FMA'), ('MOV', 'MOV')], max_length=3),
        ),
        migrations.AlterField(
            model_name='paletecontrol',
            name='loc_atual',
            field=models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('CTG', 'CTG'), ('GVR', 'GVR'), ('VIX', 'VIX'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('BMA', 'BMA'), ('BPE', 'BPE'), ('BEL', 'BEL'), ('BPB', 'BPB'), ('SLZ', 'SLZ'), ('BAL', 'BAL'), ('THE', 'THE'), ('FMA', 'FMA'), ('MOV', 'MOV')], max_length=3),
        ),
        migrations.AlterField(
            model_name='registraterceirizados',
            name='filial',
            field=models.CharField(choices=[('1', 'SPO'), ('2', 'REC'), ('3', 'SSA'), ('4', 'FOR'), ('5', 'MCZ'), ('6', 'NAT'), ('7', 'JPA'), ('8', 'AJU'), ('9', 'VDC'), ('10', 'CTG'), ('11', 'GVR'), ('12', 'VIX'), ('13', 'TCO'), ('14', 'UDI'), ('50', 'VIX'), ('20', 'SPO'), ('21', 'SPO'), ('20', 'CTG'), ('21', 'TCO'), ('22', 'UDI'), ('23', 'TMA'), ('24', 'VIX'), ('50', 'VIX'), ('30', 'BMA'), ('31', 'BPE'), ('32', 'BEL'), ('33', 'BPB'), ('34', 'SLZ'), ('35', 'BAL'), ('36', 'THE'), ('52', 'THE'), ('40', 'FMA'), ('0', 'MOV')], max_length=3),
        ),
        migrations.AlterField(
            model_name='solicitacoescompras',
            name='filial',
            field=models.CharField(choices=[('1', 'SPO'), ('2', 'REC'), ('3', 'SSA'), ('4', 'FOR'), ('5', 'MCZ'), ('6', 'NAT'), ('7', 'JPA'), ('8', 'AJU'), ('9', 'VDC'), ('10', 'CTG'), ('11', 'GVR'), ('12', 'VIX'), ('13', 'TCO'), ('14', 'UDI'), ('50', 'VIX'), ('20', 'SPO'), ('21', 'SPO'), ('20', 'CTG'), ('21', 'TCO'), ('22', 'UDI'), ('23', 'TMA'), ('24', 'VIX'), ('50', 'VIX'), ('30', 'BMA'), ('31', 'BPE'), ('32', 'BEL'), ('33', 'BPB'), ('34', 'SLZ'), ('35', 'BAL'), ('36', 'THE'), ('52', 'THE'), ('40', 'FMA'), ('0', 'MOV')], max_length=3),
        ),
        migrations.AlterField(
            model_name='solicmovpalete',
            name='destino',
            field=models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('CTG', 'CTG'), ('GVR', 'GVR'), ('VIX', 'VIX'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('BMA', 'BMA'), ('BPE', 'BPE'), ('BEL', 'BEL'), ('BPB', 'BPB'), ('SLZ', 'SLZ'), ('BAL', 'BAL'), ('THE', 'THE'), ('FMA', 'FMA'), ('MOV', 'MOV')], max_length=3),
        ),
        migrations.AlterField(
            model_name='solicmovpalete',
            name='origem',
            field=models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('CTG', 'CTG'), ('GVR', 'GVR'), ('VIX', 'VIX'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('BMA', 'BMA'), ('BPE', 'BPE'), ('BEL', 'BEL'), ('BPB', 'BPB'), ('SLZ', 'SLZ'), ('BAL', 'BAL'), ('THE', 'THE'), ('FMA', 'FMA'), ('MOV', 'MOV')], max_length=3),
        ),
        migrations.AlterField(
            model_name='ticketchamado',
            name='filial',
            field=models.CharField(blank=True, choices=[('1', 'SPO'), ('2', 'REC'), ('3', 'SSA'), ('4', 'FOR'), ('5', 'MCZ'), ('6', 'NAT'), ('7', 'JPA'), ('8', 'AJU'), ('9', 'VDC'), ('10', 'CTG'), ('11', 'GVR'), ('12', 'VIX'), ('13', 'TCO'), ('14', 'UDI'), ('50', 'VIX'), ('20', 'SPO'), ('21', 'SPO'), ('20', 'CTG'), ('21', 'TCO'), ('22', 'UDI'), ('23', 'TMA'), ('24', 'VIX'), ('50', 'VIX'), ('30', 'BMA'), ('31', 'BPE'), ('32', 'BEL'), ('33', 'BPB'), ('34', 'SLZ'), ('35', 'BAL'), ('36', 'THE'), ('52', 'THE'), ('40', 'FMA'), ('0', 'MOV')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='filial',
            field=models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('CTG', 'CTG'), ('GVR', 'GVR'), ('VIX', 'VIX'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('BMA', 'BMA'), ('BPE', 'BPE'), ('BEL', 'BEL'), ('BPB', 'BPB'), ('SLZ', 'SLZ'), ('BAL', 'BAL'), ('THE', 'THE'), ('FMA', 'FMA'), ('MOV', 'MOV')], max_length=3),
        ),
    ]
