# Generated by Django 3.2.6 on 2021-09-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0002_auto_20210920_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='empresa',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='placa2',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
