# Generated by Django 3.2.6 on 2021-09-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0002_auto_20210913_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='placa',
            field=models.CharField(max_length=20),
        ),
    ]
