# Generated by Django 3.2.6 on 2021-09-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0002_auto_20210901_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='placa2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
