# Generated by Django 3.2.6 on 2021-09-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0003_auto_20210913_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='empresa',
            field=models.CharField(max_length=100),
        ),
    ]
