# Generated by Django 3.2.6 on 2021-09-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0003_auto_20210921_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='garagem',
            field=models.CharField(choices=[('SPO', '1'), ('REC', '2'), ('SSA', '3'), ('FOR', '4'), ('MCZ', '5'), ('NAT', '6'), ('JPA', '7'), ('AJU', '8'), ('VDC', '9'), ('MG', '10'), ('CTG', '20'), ('TCO', '21'), ('UDI', '22'), ('TNA', '23'), ('VIX', '24')], max_length=5),
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='tipo_func',
            new_name='tipo_mot'
        )
    ]
