# Generated by Django 3.2.6 on 2021-09-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0003_alter_cadastro_placa2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='hr_chegada',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='hr_saida',
            field=models.DateTimeField(blank=True),
        ),
    ]
