# Generated by Django 3.2.6 on 2021-09-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0004_auto_20210908_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='hr_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
