# Generated by Django 3.2.6 on 2021-09-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0004_alter_cadastro_garagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='tipo_mot',
            new_name='tipo_func',
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='garagem',
            field=models.CharField(choices=[('1', 'SPO'), ('2', 'REC'), ('3', 'SSA'), ('4', 'FOR'), ('5', 'MCZ'), ('6', 'NAT'), ('7', 'JPA'), ('8', 'AJU'), ('9', 'VDC'), ('10', 'MG'), ('20', 'CTG'), ('21', 'TCO'), ('22', 'UDI'), ('23', 'TNA'), ('24', 'VIX')], max_length=5),
        ),
    ]
