# Generated by Django 3.2.6 on 2021-09-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0005_auto_20210922_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='tipo_func',
            new_name='tipo_mot',
        ),
    ]
