# Generated by Django 3.2.6 on 2021-09-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0005_alter_cadastro_hr_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='hr_saida',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
