# Generated by Django 3.2.6 on 2021-09-14 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0005_alter_cadastro_hr_chegada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='hr_chegada',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 14, 11, 23, 29, 344308, tzinfo=utc)),
        ),
    ]
