# Generated by Django 3.2.6 on 2021-09-09 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portaria', '0006_alter_cadastro_hr_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='autor',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='hr_saida',
            field=models.DateTimeField(blank=True),
        ),
    ]
