# Generated by Django 3.2.6 on 2021-09-28 16:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0009_motorista_veiculos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='cep',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='telefone',
            field=models.IntegerField(max_length=11),
        ),
        migrations.CreateModel(
            name='ChecklistFrota',
            fields=[
                ('idchecklist', models.BigAutoField(primary_key=True, serialize=False)),
                ('datachecklist', models.DateField(default=django.utils.timezone.now)),
                ('placacarreta', models.CharField(blank=True, max_length=7, null=True)),
                ('kmanterior', models.IntegerField()),
                ('kmatual', models.IntegerField()),
                ('horimetro', models.CharField(max_length=10)),
                ('p1_1', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p1_2', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_1', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_2', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_3', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_4', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_5', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_6', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_7', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_8', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_9', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_10', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_11', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_12', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_13', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_14', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_15', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_16', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_17', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_18', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_19', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_20', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_21', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_22', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_23', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p2_24', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p3_1', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p3_2', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p3_3', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p3_4', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p3_5', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p3_6', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p3_7', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('p3_8', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('motoristaveic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.motorista')),
                ('placaveic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.veiculos')),
            ],
        ),
    ]
