# Generated by Django 3.2.6 on 2021-09-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0010_auto_20210909_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='filial',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro',
            name='tipo_func',
            field=models.CharField(choices=[('INTERNO', 'INTERNO'), ('AGREGADO', 'AGREGADO')], default='EXTERNO', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='empresa',
            field=models.CharField(max_length=100),
        ),
    ]
