# Generated by Django 3.2.6 on 2021-09-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0010_auto_20210928_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='garagem',
            new_name='destino',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='origem',
            field=models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('MG', 'MG'), ('CTG', 'CTG'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TNA', 'TNA'), ('VIX', 'VIX')], default='a', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='codigotpveic',
            field=models.CharField(choices=[('1', 'VAN_PASSAGEIROS'), ('2', 'CAMINHAO'), ('3', 'CAVALO'), ('4', 'CARRETA'), ('5', 'VUC'), ('6', 'BITRUCK'), ('7', 'TOCO'), ('8', '3/4'), ('9', 'TRUCK'), ('10', 'VEICULO_APOIO'), ('11', 'PASSAGEIRO'), ('12', 'PASSAGEIRO_AUTOMOVEL')], max_length=5),
        ),
    ]
