# Generated by Django 3.2.6 on 2021-09-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0011_auto_20210928_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='destino',
            field=models.CharField(blank=True, choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('MG', 'MG'), ('CTG', 'CTG'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TNA', 'TNA'), ('VIX', 'VIX')], max_length=5, null=True),
        ),
    ]
