# Generated by Django 3.2.6 on 2021-10-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0012_alter_cadastro_destino'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfServicoPj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=50)),
                ('salario', models.IntegerField()),
                ('premios_faculdade', models.IntegerField()),
                ('ajuda_custo', models.IntegerField()),
                ('adiantamento', models.IntegerField()),
                ('convenio', models.IntegerField()),
                ('total_a_pagar', models.IntegerField()),
                ('cpf_cnpj', models.IntegerField()),
                ('banco', models.IntegerField()),
                ('ag', models.IntegerField()),
                ('conta', models.IntegerField()),
                ('op', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
