# Generated by Django 3.2.6 on 2021-10-05 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0013_nfservicopj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfservicopj',
            name='salario',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
