# Generated by Django 3.2.6 on 2021-10-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0015_alter_nfservicopj_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfservicopj',
            name='salario',
            field=models.IntegerField(),
        ),
    ]
