# Generated by Django 3.2.6 on 2021-10-05 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0016_alter_nfservicopj_salario'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncPj',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unidade', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=50)),
                ('salario', models.IntegerField()),
                ('cpf_cnpj', models.IntegerField()),
                ('banco', models.IntegerField()),
                ('ag', models.IntegerField()),
                ('conta', models.IntegerField()),
                ('op', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='nfservicopj',
            name='ag',
        ),
        migrations.RemoveField(
            model_name='nfservicopj',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='nfservicopj',
            name='conta',
        ),
        migrations.RemoveField(
            model_name='nfservicopj',
            name='cpf_cnpj',
        ),
        migrations.RemoveField(
            model_name='nfservicopj',
            name='email',
        ),
        migrations.RemoveField(
            model_name='nfservicopj',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='nfservicopj',
            name='op',
        ),
        migrations.RemoveField(
            model_name='nfservicopj',
            name='salario',
        ),
        migrations.RemoveField(
            model_name='nfservicopj',
            name='total_a_pagar',
        ),
        migrations.RemoveField(
            model_name='nfservicopj',
            name='unidade',
        ),
        migrations.AlterField(
            model_name='nfservicopj',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='nfservicopj',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portaria.funcpj'),
            preserve_default=False,
        ),
    ]
