# Generated by Django 3.2.6 on 2021-10-06 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0017_auto_20211005_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfservicopj',
            name='data_emissao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
