# Generated by Django 3.2.6 on 2021-10-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0019_checklistfrota_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistfrota',
            name='p1_1',
            field=models.BooleanField(verbose_name='Uniforme da Empresa'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p1_2',
            field=models.BooleanField(verbose_name='Motorista identificado por crachá'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_1',
            field=models.BooleanField(verbose_name='Lanterna do farol dianteiro funcionando?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_10',
            field=models.BooleanField(verbose_name='Óleo de freio está no nível?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_11',
            field=models.BooleanField(verbose_name='Óleo de motor está no nível?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_12',
            field=models.BooleanField(verbose_name='Verificado todas as luzes de advertências?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_13',
            field=models.BooleanField(verbose_name='Verificado o freio de emergência?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_14',
            field=models.BooleanField(verbose_name='Verificado o alarme sonoro da ré?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_15',
            field=models.BooleanField(verbose_name='Verificado se existe vazamentos de óleo de motor?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_16',
            field=models.BooleanField(verbose_name='Verificado se existe vazamento de ar?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_17',
            field=models.BooleanField(verbose_name='Verificado se existe vazamento de óleo hidráulico?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_18',
            field=models.BooleanField(verbose_name='Verificado se existe vazamento de água no radiador?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_19',
            field=models.BooleanField(verbose_name='Verificado se as mangueiras estão em condições boas?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_2',
            field=models.BooleanField(verbose_name='Farol baixo funcionando?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_20',
            field=models.BooleanField(verbose_name='Pneus em boas condições?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_21',
            field=models.BooleanField(verbose_name='As lonas de freio estão em boas condições?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_22',
            field=models.BooleanField(verbose_name='Os estepes estão bons?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_23',
            field=models.BooleanField(verbose_name='A suspensão está em condições perfeitas?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_24',
            field=models.BooleanField(verbose_name='O carro está limpo e higienizado?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_3',
            field=models.BooleanField(verbose_name='Farol alto funcionando?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_4',
            field=models.BooleanField(verbose_name='Lanterna direita funcionando?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_5',
            field=models.BooleanField(verbose_name='Lanterna esquerda funcionando?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_6',
            field=models.BooleanField(verbose_name='Lanternas traseiras funcionando?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_7',
            field=models.BooleanField(verbose_name='Luz de ré funcionando?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_8',
            field=models.BooleanField(verbose_name='Retrovisores estão em perfeito estado?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_9',
            field=models.BooleanField(verbose_name='Água do radiador está no nível?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p3_1',
            field=models.BooleanField(verbose_name='Foi verificado as luzes de advertência das laterais?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p3_2',
            field=models.BooleanField(verbose_name='Foi verificado o lacre da placa?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p3_3',
            field=models.BooleanField(verbose_name='Foi verificado se o aparelho thermoking apresenta falhas?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p3_4',
            field=models.BooleanField(verbose_name='Foi verificado a carroceria, assoalho e baú?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p3_5',
            field=models.BooleanField(verbose_name='Foi verificado a luz de freio?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p3_6',
            field=models.BooleanField(verbose_name='Foi verificado a luz de ré?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p3_7',
            field=models.BooleanField(verbose_name='Foi verificado se as luzes da lanterna traseira direita funciona?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p3_8',
            field=models.BooleanField(verbose_name='Foi verificado se as luzes da lanterna traseira esquerda funciona?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='teste',
            field=models.BooleanField(verbose_name='testando'),
        ),
    ]
