# Generated by Django 3.2.6 on 2021-10-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0020_auto_20211015_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcpj',
            old_name='cpf_cnpj',
            new_name='cnpj',
        ),
        migrations.RemoveField(
            model_name='funcpj',
            name='unidade',
        ),
        migrations.AddField(
            model_name='funcpj',
            name='cpf',
            field=models.IntegerField(default=11111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcpj',
            name='filial',
            field=models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('MG', 'MG'), ('CTG', 'CTG'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TNA', 'TNA'), ('VIX', 'VIX')], default='1111', max_length=3),
            preserve_default=False,
        ),
    ]
