# Generated by Django 3.2.6 on 2021-10-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0021_auto_20211015_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcpj',
            name='tipo_contrato',
            field=models.CharField(choices=[('PF', 'PF'), ('PJ', 'PJ')], default='111', max_length=2),
            preserve_default=False,
        ),
    ]
