# Generated by Django 3.2.6 on 2021-10-20 11:33

from django.db import migrations, models
import django.db.models.deletion
import portaria.models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0023_nfservicopj_outros_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcpj',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='funcpj',
            name='cnpj',
            field=models.CharField(max_length=14, validators=[portaria.models.only_int]),
        ),
        migrations.AlterField(
            model_name='funcpj',
            name='cpf',
            field=models.CharField(max_length=11, validators=[portaria.models.only_int]),
        ),
        migrations.AlterField(
            model_name='nfservicopj',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='portaria.funcpj'),
        ),
    ]
