# Generated by Django 3.2.6 on 2021-10-21 09:16

from django.db import migrations, models
import django.db.models.deletion
import portaria.models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0024_auto_20211020_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistfrota',
            name='teste',
        ),
        migrations.RemoveField(
            model_name='veiculos',
            name='codmotorista',
        ),
        migrations.AlterField(
            model_name='motorista',
            name='CPF',
            field=models.CharField(max_length=11, validators=[portaria.models.only_int]),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='RG',
            field=models.CharField(max_length=20, validators=[portaria.models.only_int]),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cep',
            field=models.CharField(max_length=8, validators=[portaria.models.only_int]),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='telefone',
            field=models.CharField(max_length=11, validators=[portaria.models.only_int]),
        ),
        migrations.AlterField(
            model_name='nfservicopj',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.funcpj'),
        ),
    ]
