# Generated by Django 3.2.6 on 2021-10-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0025_auto_20211021_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculos',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='veiculos',
            name='garagem',
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='codigotpveic',
            field=models.CharField(choices=[('1', 'CAMINHÃO TOCO 3/4'), ('2', 'CAMINHÃO TOCO'), ('3', 'CAMINHÃO 3/4'), ('4', 'CAMINHONETE/UTILITARIO'), ('5', 'CAMINHÃO TRUCK'), ('6', 'PASSEIO'), ('7', 'CAVALO'), ('8', 'CARRETA'), ('9', 'CAMINHÃO BI TRUCK '), ('10', 'CAVALO '), ('11', 'CAMINHAO LEVE'), ('12', 'SEMI ROBOQUE'), ('13', 'CAMINHÃO FURGÃO'), ('14', 'CAMINHÃO TRUCK '), ('15', 'CAMINHOTE'), ('16', 'CAMINHONETE/FURGAO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='filial',
            field=models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('MG', 'MG'), ('CTG', 'CTG'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TNA', 'TNA'), ('VIX', 'VIX')], max_length=3),
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='obsveic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
