# Generated by Django 3.2.6 on 2021-10-22 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portaria', '0029_alter_cadastro_hr_chegada'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfservicopj',
            name='autor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nfservicopj',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.funcpj'),
        ),
    ]
