# Generated by Django 3.2.6 on 2021-10-26 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0031_remove_motorista_codigoveic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManutencaoFrota',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tp_manutencao', models.CharField(choices=[('PREVENTIVA', 'PREVENTIVA'), ('CORRETIVA', 'CORRETIVA')], max_length=10, verbose_name='Tipo manutenção')),
                ('local_manu', models.CharField(choices=[('I', 'INTERNO'), ('E', 'EXTERNO')], max_length=1, verbose_name='Local manutenção')),
                ('dt_ult_manutencao', models.DateField(verbose_name='Data da última manutenção')),
                ('dt_entrada', models.DateField()),
                ('dt_saida', models.DateField(blank=True, null=True)),
                ('dias_veic_parado', models.DateField(blank=True, null=True)),
                ('km_ult_troca_oleo', models.IntegerField(verbose_name='Kilometragem da última troca de óleo')),
                ('tp_servico', models.CharField(choices=[('TROCA_OLEO', 'TROCA_OLEO'), ('PNEUS', 'PNEUS'), ('FREIOS', 'FREIOS')], max_length=10, verbose_name='Tipo serviço')),
                ('valor_maodeobra', models.FloatField(verbose_name='Valor mão de obra')),
                ('valor_peca', models.FloatField(verbose_name='Valor peça')),
                ('filial', models.CharField(choices=[('SPO', 'SPO'), ('VDC', 'VDC')], max_length=3)),
                ('socorro', models.BooleanField()),
                ('prev_entrega', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.veiculos')),
            ],
        ),
    ]
