# Generated by Django 3.2.6 on 2021-10-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0032_manutencaofrota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencaofrota',
            name='dias_veic_parado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='manutencaofrota',
            name='dt_ult_manutencao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da última manutenção'),
        ),
    ]
