# Generated by Django 3.2.6 on 2021-10-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0033_auto_20211027_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencaofrota',
            name='valor_maodeobra',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor mão de obra'),
        ),
        migrations.AlterField(
            model_name='manutencaofrota',
            name='valor_peca',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor peça'),
        ),
    ]
