# Generated by Django 3.2.6 on 2021-10-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0034_auto_20211027_1545'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaletControl',
            new_name='PaleteControl',
        ),
        migrations.AlterModelOptions(
            name='paletecontrol',
            options={'verbose_name': 'PaleteControl', 'verbose_name_plural': 'PaleteControl'},
        ),
    ]
