# Generated by Django 3.2.6 on 2021-10-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0035_auto_20211027_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorista',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='veiculos',
            name='capacidadetanqueveic',
        ),
        migrations.RemoveField(
            model_name='veiculos',
            name='condicaoveic',
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='tipo_mot',
            field=models.CharField(choices=[('INTERNO', 'INTERNO'), ('AGREGADO', 'AGREGADO'), ('SEM_VINCULO', 'SEM_VINCULO')], max_length=11),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='filial',
            field=models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('MG', 'MG'), ('CTG', 'CTG'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TNA', 'TNA'), ('VIX', 'VIX')], max_length=3),
        ),
    ]
