# Generated by Django 3.2.6 on 2021-10-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0036_auto_20211028_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motorista',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='manutencaofrota',
            name='status',
            field=models.CharField(choices=[('ANDAMENTO', 'ANDAMENTO'), ('PENDENTE CONFIRMAR', 'PENDENTE CONFIRMAR'), ('ATRASADO', 'ATRASADO'), ('CONCLUIDO', 'CONCLUIDO')], default='1', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manutencaofrota',
            name='tp_servico',
            field=models.CharField(choices=[('TROCA_OLEO', (('troca', 'troca'), ('oleo', 'oleo'))), ('PNEUS', 'PNEUS'), ('FREIOS', 'FREIOS')], max_length=10, verbose_name='Tipo serviço'),
        ),
    ]
