# Generated by Django 3.2.6 on 2021-10-29 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portaria', '0038_auto_20211029_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServJoinManu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_svs', models.CharField(max_length=20)),
                ('pub_date', models.DateField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.manutencaofrota')),
            ],
        ),
    ]
