# Generated by Django 3.2.6 on 2021-11-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0039_servjoinmanu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro',
            options={'verbose_name': 'Cadastro', 'verbose_name_plural': 'Cadastro'},
        ),
        migrations.AlterModelOptions(
            name='checklistfrota',
            options={'verbose_name': 'ChecklistFrota', 'verbose_name_plural': 'ChecklistFrota'},
        ),
        migrations.AlterModelOptions(
            name='funcpj',
            options={'verbose_name': 'Funcpj', 'verbose_name_plural': 'Funcpj'},
        ),
        migrations.AlterModelOptions(
            name='manutencaofrota',
            options={'verbose_name': 'ManutencaoFrota', 'verbose_name_plural': 'ManutencaoFrota'},
        ),
        migrations.AlterModelOptions(
            name='motorista',
            options={'ordering': ['nome'], 'verbose_name': 'Motorista', 'verbose_name_plural': 'Motorista'},
        ),
        migrations.AlterModelOptions(
            name='nfservicopj',
            options={'verbose_name': 'NfServicoPj', 'verbose_name_plural': 'NfServicoPj'},
        ),
        migrations.AlterModelOptions(
            name='servjoinmanu',
            options={'verbose_name': 'ServJoinManu', 'verbose_name_plural': 'ServJoinManu'},
        ),
        migrations.AlterModelOptions(
            name='veiculos',
            options={'verbose_name': 'Veiculos', 'verbose_name_plural': 'Veiculos'},
        ),
        migrations.AlterField(
            model_name='manutencaofrota',
            name='tp_servico',
            field=models.CharField(choices=[('TROCA_OLEO', (('troca', 'troca'), ('oleo', 'oleo'))), ('PNEUS', 'PNEUS'), ('FREIOS', 'FREIOS'), ('aaaa', 'aaaaa'), ('dasdasd', 'dasdasd')], max_length=10, verbose_name='Tipo serviço'),
        ),
    ]
