# Generated by Django 3.2.6 on 2021-11-04 13:40

from django.db import migrations, models
import portaria.models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0040_auto_20211104_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardFuncionario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('celular', models.IntegerField(validators=[portaria.models.only_int])),
            ],
        ),
    ]
