# Generated by Django 3.2.6 on 2021-11-04 14:54

from django.db import migrations, models
import portaria.models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0041_cardfuncionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardfuncionario',
            name='celular',
            field=models.CharField(max_length=11, validators=[portaria.models.only_int]),
        ),
    ]
