# Generated by Django 3.2.6 on 2021-11-05 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portaria', '0042_alter_cardfuncionario_celular'),
    ]

    operations = [
        migrations.CreateModel(
            name='pj13',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo_meses', models.IntegerField()),
                ('valor', models.FloatField()),
                ('pgto_parc_1', models.DateField()),
                ('pgto_parc_2', models.DateField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.funcpj')),
            ],
        ),
    ]
