# Generated by Django 3.2.6 on 2021-11-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0043_pj13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pj13',
            name='pgto_parc_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pj13',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
