# Generated by Django 3.2.6 on 2021-11-08 13:06

from django.db import migrations, models
import portaria.models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0045_feriaspj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriaspj',
            name='periodo',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[portaria.models.only_int]),
        ),
        migrations.AlterField(
            model_name='feriaspj',
            name='valor_pagar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
