# Generated by Django 3.2.6 on 2021-11-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0047_remove_feriaspj_valor_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriaspj',
            name='proximas_ferias',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='feriaspj',
            name='alerta_venc_enviado',
            field=models.BooleanField(default=0),
        ),
    ]
