# Generated by Django 3.2.6 on 2021-11-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0049_auto_20211110_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feriaspj',
            old_name='agendamento',
            new_name='agendamento_fim',
        ),
        migrations.AddField(
            model_name='feriaspj',
            name='agendamento_ini',
            field=models.DateField(blank=True, null=True),
        ),
    ]
