# Generated by Django 3.2.6 on 2021-11-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0050_auto_20211110_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriaspj',
            name='valor_integral',
            field=models.FloatField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feriaspj',
            name='valor_parcial1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feriaspj',
            name='valor_parcial2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
