# Generated by Django 3.2.6 on 2021-11-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0051_auto_20211110_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriaspj',
            name='tp_pgto',
            field=models.CharField(choices=[('INTEGRAL', 'INTEGRAL'), ('PARCIAL', 'PARCIAL')], default='1', max_length=8),
            preserve_default=False,
        ),
    ]
