# Generated by Django 3.2.6 on 2021-11-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0052_feriaspj_tp_pgto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriaspj',
            name='quitado',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='feriaspj',
            name='valor_integral',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
