# Generated by Django 3.2.6 on 2021-11-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0053_auto_20211110_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriaspj',
            name='dt_quitacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feriaspj',
            name='funcionario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='portaria.funcpj'),
        ),
    ]
