# Generated by Django 3.2.6 on 2021-11-12 08:53

from django.db import migrations, models
import django.utils.timezone
import portaria.models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0054_auto_20211110_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcpj',
            name='admissao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='funcpj',
            name='cpf_cnpj',
            field=models.CharField(max_length=14, validators=[portaria.models.only_int]),
        ),
    ]
