# Generated by Django 3.2.6 on 2021-11-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0057_auto_20211112_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardfuncionario',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
