# Generated by Django 3.2.6 on 2021-11-12 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0058_auto_20211112_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='paletecontrol',
            name='empresa',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='portaria.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paletecontrol',
            name='mov_palete_fk',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='portaria.movpalete'),
            preserve_default=False,
        ),
    ]
