# Generated by Django 3.2.6 on 2021-11-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0058_cardfuncionario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMonitoramento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assunto', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('cc', models.CharField(max_length=200)),
                ('dt_envio', models.DateField()),
                ('email_id', models.CharField(max_length=50, unique=True)),
                ('ult_resp', models.TextField(blank=True, null=True)),
                ('ult_rest_dt', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
