# Generated by Django 3.2.6 on 2021-11-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0059_emailmonitoramento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmonitoramento',
            name='cc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
