# Generated by Django 3.2.6 on 2021-11-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0060_remove_paletecontrol_mov_palete_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='intex',
            field=models.CharField(choices=[('INTERNO', 'INTERNO'), ('EXTERNO', 'EXTERNO')], default='1', max_length=7),
            preserve_default=False,
        ),
    ]
