# Generated by Django 3.2.6 on 2021-11-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0061_auto_20211124_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmonitoramento',
            name='ult_resp_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailmonitoramento',
            name='email_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
