# Generated by Django 3.2.6 on 2021-12-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0062_auto_20211126_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmonitoramento',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'ABERTO'), ('ANDAMENTO', 'ANDAMENTO'), ('CONCLUIDO', 'CONCLUIDO'), ('CANCELADO', 'CANCELADO')], default='1', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketmonitoramento',
            name='tags',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
