# Generated by Django 3.2.6 on 2021-12-08 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portaria', '0063_auto_20211206_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketmonitoramento',
            old_name='tags',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='ticketmonitoramento',
            old_name='cliente',
            new_name='destinatario',
        ),
        migrations.AddField(
            model_name='ticketmonitoramento',
            name='cte',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketmonitoramento',
            name='remetente',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketmonitoramento',
            name='solicitante',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='solicitante', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketmonitoramento',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsavel', to=settings.AUTH_USER_MODEL),
        ),
    ]
