# Generated by Django 3.2.6 on 2021-11-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0063_cliente_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paletecontrol',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='paletecontrol',
            name='posse_bora',
        ),
    ]
