# Generated by Django 3.2.6 on 2021-12-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0064_auto_20211208_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmonitoramento',
            name='msg_id',
            field=models.CharField(default='1', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
