# Generated by Django 3.2.6 on 2021-12-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0065_ticketmonitoramento_msg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmonitoramento',
            name='cc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ticketmonitoramento',
            name='categoria',
            field=models.CharField(choices=[('Aguardando Recebimento', 'Aguardando Recebimento'), ('Dae', 'Dae'), ('Descarga', 'Descarga'), ('Devolução Parcial', 'Devolução Parcial'), ('Devolução Total', 'Devolução Total'), ('Diaria autorizada', 'Diaria autorizada'), ('Dif. Peso', 'Dif. Peso'), ('Entrega Realizada', 'Entrega Realizada'), ('Fora de Horário', 'Fora de Horário'), ('Fora de Rota', 'Fora de Rota'), ('Imprópria', 'Imprópria'), ('Merc. nao embar.', 'Merc. nao embar.'), ('Prorrogação de Boleto', 'Prorrogação de Boleto'), ('Reentrega', 'Reentrega'), ('Refaturamento', 'Refaturamento'), ('Reversa', 'Reversa'), ('Sem Agendamento', 'Sem Agendamento'), ('Sem Pedido', 'Sem Pedido'), ('Veículo em rota', 'Veículo em rota'), ('Veículo Quebrado', 'Veículo Quebrado')], max_length=100),
        ),
    ]
