# Generated by Django 3.2.6 on 2022-01-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0066_auto_20211215_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicosManut',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grupo_servico', models.CharField(max_length=50, verbose_name='Grupo')),
                ('tipo_servico', models.CharField(max_length=50, verbose_name='Tipo Servico')),
            ],
        ),
        migrations.AddField(
            model_name='checklistfrota',
            name='obs',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
    ]
