# Generated by Django 3.2.6 on 2022-01-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0067_auto_20220106_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencaofrota',
            name='tp_servico',
            field=models.CharField(max_length=10, verbose_name='Tipo serviço'),
        ),
        migrations.AlterField(
            model_name='ticketmonitoramento',
            name='nome_tkt',
            field=models.CharField(error_messages={'unique': 'Já existe ticket criado para este CTE'}, max_length=100, unique=True),
        ),
    ]
