# Generated by Django 3.2.6 on 2022-01-10 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0068_auto_20220107_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servjoinmanu',
            name='id_svs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.tiposervicosmanut'),
        ),
    ]
