# Generated by Django 3.2.6 on 2022-01-10 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0069_alter_servjoinmanu_id_svs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencaofrota',
            name='tp_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencao', to='portaria.servjoinmanu'),
        ),
    ]
