# Generated by Django 3.2.6 on 2022-01-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0070_alter_manutencaofrota_tp_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencaofrota',
            name='tp_servico',
            field=models.CharField(max_length=10, verbose_name='Tipo serviço'),
        ),
    ]
