# Generated by Django 3.2.6 on 2022-01-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0071_alter_manutencaofrota_tp_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistfrota',
            name='placacarreta2',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
