# Generated by Django 3.2.6 on 2022-01-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0064_auto_20211117_1305'),
        ('portaria', '0075_auto_20220112_1417'),
    ]

    operations = [
    ]
