# Generated by Django 3.2.6 on 2022-01-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0076_merge_0064_auto_20211117_1305_0075_auto_20220112_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfservicopj',
            name='data_pagamento',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcpj',
            name='adiantamento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcpj',
            name='admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcpj',
            name='ag',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcpj',
            name='ajuda_custo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcpj',
            name='banco',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcpj',
            name='conta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcpj',
            name='filial',
            field=models.CharField(blank=True, choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('MG', 'MG'), ('CTG', 'CTG'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TNA', 'TNA'), ('VIX', 'VIX')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='funcpj',
            name='op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcpj',
            name='salario',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
