# Generated by Django 3.2.6 on 2022-01-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0079_mailspj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailspj',
            name='data_pagamento',
            field=models.DateField(),
        ),
    ]
