# Generated by Django 3.2.6 on 2022-01-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0081_alter_emailchamado_dt_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailchamado',
            name='ult_resp_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
