# Generated by Django 3.2.6 on 2022-01-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0082_alter_emailchamado_ult_resp_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmonitoramento',
            name='ult_resp_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
