# Generated by Django 3.2.6 on 2022-01-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0083_alter_emailmonitoramento_ult_resp_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmonitoramento',
            name='dt_envio',
            field=models.DateTimeField(),
        ),
    ]
