# Generated by Django 3.2.6 on 2022-01-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0084_alter_emailmonitoramento_dt_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmonitoramento',
            name='filial',
            field=models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('MG', 'MG'), ('CTG', 'CTG'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TNA', 'TNA'), ('VIX', 'VIX')], default='SPO', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketmonitoramento',
            name='destinatario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketmonitoramento',
            name='remetente',
            field=models.CharField(max_length=100),
        ),
    ]
