# Generated by Django 3.2.6 on 2022-01-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0086_ticketmonitoramento_tp_docto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmonitoramento',
            name='tp_docto',
            field=models.CharField(choices=[('8', 'NFS'), ('57', 'CTE')], max_length=3),
        ),
    ]
