# Generated by Django 3.2.6 on 2022-02-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0088_alter_ticketmonitoramento_filial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOcorenciasMonit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('rsocial', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
