# Generated by Django 3.2.6 on 2022-02-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0089_emailocorenciasmonit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmonitoramento',
            name='assunto',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ticketmonitoramento',
            name='nome_tkt',
            field=models.CharField(error_messages={'unique': 'Já existe ticket criado para este CTE'}, max_length=150, unique=True),
        ),
    ]
