# Generated by Django 3.2.6 on 2022-03-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0090_auto_20220210_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='notas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
