# Generated by Django 3.2.6 on 2022-03-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0092_romxml_skurefxml'),
    ]

    operations = [
        migrations.AddField(
            model_name='romxml',
            name='peso',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='romxml',
            name='vlr_nf',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='romxml',
            name='volume',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
