# Generated by Django 3.2.6 on 2022-03-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0094_romxml_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='romxml',
            name='municipio',
            field=models.CharField(default='sp', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='romxml',
            name='uf',
            field=models.CharField(default='sp', max_length=2),
            preserve_default=False,
        ),
    ]
