# Generated by Django 3.2.6 on 2022-03-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0095_auto_20220304_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='romxml',
            name='printed',
            field=models.BooleanField(default=False),
        ),
    ]
