# Generated by Django 3.2.6 on 2022-03-04 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0096_romxml_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='romxml',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 16, 45, 57, 579856)),
        ),
    ]
