# Generated by Django 3.2.6 on 2022-03-08 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0097_romxml_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manutencaofrota',
            name='km_ult_troca_oleo',
        ),
        migrations.RemoveField(
            model_name='manutencaofrota',
            name='valor_maodeobra',
        ),
        migrations.RemoveField(
            model_name='manutencaofrota',
            name='valor_peca',
        ),
        migrations.AddField(
            model_name='manutencaofrota',
            name='km_atual',
            field=models.IntegerField(default=1, verbose_name='Kilometragem atual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servjoinmanu',
            name='fornecedor',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servjoinmanu',
            name='produto',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servjoinmanu',
            name='valor_maodeobra',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor mão de obra'),
        ),
        migrations.AddField(
            model_name='servjoinmanu',
            name='valor_peca',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor peça'),
        ),
        migrations.AlterField(
            model_name='romxml',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
