# Generated by Django 3.2.6 on 2022-03-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0098_auto_20220308_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servjoinmanu',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servjoinmanu',
            name='produto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
