# Generated by Django 3.2.6 on 2022-03-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0099_auto_20220308_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='servjoinmanu',
            name='local_manu',
            field=models.CharField(choices=[('I', 'INTERNO'), ('E', 'EXTERNO')], default='I', max_length=1, verbose_name='Local manutenção'),
            preserve_default=False,
        ),
    ]
