# Generated by Django 3.2.6 on 2022-03-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0100_servjoinmanu_local_manu'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistfrota',
            name='filial',
            field=models.CharField(choices=[('1', 'SPO'), ('2', 'REC'), ('3', 'SSA'), ('4', 'FOR'), ('5', 'MCZ'), ('6', 'NAT'), ('7', 'JPA'), ('8', 'AJU'), ('9', 'VDC'), ('10', 'MG'), ('20', 'CTG'), ('21', 'TCO'), ('22', 'UDI'), ('23', 'TMA'), ('24', 'VIX'), ('30', 'BMA'), ('31', 'BPE'), ('32', 'BEL'), ('33', 'BPB'), ('34', 'SLZ'), ('35', 'BAL'), ('36', 'THE')], default='1', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistfrota',
            name='p3_9',
            field=models.BooleanField(default='1', verbose_name='Plotagem do veículo possui avarias?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p3_2',
            field=models.BooleanField(verbose_name='Foi verificado se o aparelho thermoking apresenta falhas?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p3_3',
            field=models.BooleanField(verbose_name='Foi verificado a carroceria, assoalho e baú?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p3_4',
            field=models.BooleanField(verbose_name='Foi verificado a luz de freio?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p3_5',
            field=models.BooleanField(verbose_name='Foi verificado a luz de ré?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p3_6',
            field=models.BooleanField(verbose_name='Foi verificado se as luzes da lanterna traseira direita funciona?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p3_7',
            field=models.BooleanField(verbose_name='Foi verificado se as luzes da lanterna traseira esquerda funciona?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p3_8',
            field=models.BooleanField(verbose_name='Veículo Plotado?'),
        ),
    ]
