# Generated by Django 3.2.6 on 2022-03-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0104_auto_20220311_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencaofrota',
            name='dt_ini_manu',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio Manutencao'),
        ),
        migrations.AlterField(
            model_name='manutencaofrota',
            name='socorro',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manutencaofrota',
            name='tp_manutencao',
            field=models.CharField(blank=True, choices=[('PREVENTIVA', 'PREVENTIVA'), ('CORRETIVA', 'CORRETIVA'), ('PRE', 'PRE')], max_length=10, null=True, verbose_name='Tipo manutenção'),
        ),
    ]
