# Generated by Django 3.2.6 on 2022-03-18 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0109_auto_20220318_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bipagemetiqueta',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='etiquetasromaneio',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
