# Generated by Django 3.2.6 on 2022-03-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0111_retornoetiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retornoetiqueta',
            name='nota_fiscal',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
