# Generated by Django 3.2.6 on 2022-03-25 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0114_etiquetaspalete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquetaspalete',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
