# Generated by Django 3.2.6 on 2022-03-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0117_etiquetaspalete_volume_conf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquetaspalete',
            name='bip_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
