# Generated by Django 3.2.6 on 2022-03-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0118_alter_etiquetaspalete_bip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquetaspalete',
            name='cod_barras',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etiquetaspalete',
            name='manifesto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p2_24',
            field=models.BooleanField(verbose_name='Limpador de parabrisa funcionando?'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='p3_6',
            field=models.BooleanField(verbose_name='Luz de ré funcionando?'),
        ),
        migrations.AlterField(
            model_name='etiquetaspalete',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
