# Generated by Django 3.2.6 on 2022-04-07 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portaria', '0121_auto_20220331_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bipagemetiqueta',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='destino',
            field=models.CharField(blank=True, choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('MG', 'MG'), ('CTG', 'CTG'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('VIX', 'VIX')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='origem',
            field=models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('MG', 'MG'), ('CTG', 'CTG'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('VIX', 'VIX')], max_length=5),
        ),
        migrations.AlterField(
            model_name='funcpj',
            name='filial',
            field=models.CharField(blank=True, choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('MG', 'MG'), ('CTG', 'CTG'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('VIX', 'VIX')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='filial',
            field=models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('MG', 'MG'), ('CTG', 'CTG'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('VIX', 'VIX')], max_length=3),
        ),
        migrations.AlterField(
            model_name='movpalete',
            name='destino',
            field=models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('MG', 'MG'), ('CTG', 'CTG'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('VIX', 'VIX')], max_length=3),
        ),
        migrations.AlterField(
            model_name='movpalete',
            name='origem',
            field=models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('MG', 'MG'), ('CTG', 'CTG'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('VIX', 'VIX')], max_length=3),
        ),
        migrations.AlterField(
            model_name='paletecontrol',
            name='loc_atual',
            field=models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('MG', 'MG'), ('CTG', 'CTG'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('VIX', 'VIX')], max_length=3),
        ),
        migrations.AlterField(
            model_name='retornoetiqueta',
            name='saida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticketchamado',
            name='filial',
            field=models.CharField(blank=True, choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('MG', 'MG'), ('CTG', 'CTG'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('VIX', 'VIX')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='filial',
            field=models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('MG', 'MG'), ('CTG', 'CTG'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('VIX', 'VIX')], max_length=3),
        ),
        migrations.CreateModel(
            name='AuthBipagemEtiqueta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('obs', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('etq_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.etiquetasdocumento')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
