# Generated by Django 3.2.6 on 2022-04-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0122_auto_20220407_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retornoetiqueta',
            name='nota_fiscal',
            field=models.CharField(max_length=15),
        ),
    ]
