# Generated by Django 3.2.6 on 2022-05-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0123_alter_justificativaentrega_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificativaentrega',
            name='cod_just',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='justificativaentrega',
            name='data_emissao',
            field=models.DateField(default='0001-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='justificativaentrega',
            name='desc_just',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
