# Generated by Django 3.2.6 on 2022-05-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0124_auto_20220502_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificativaentrega',
            name='id_garagem',
            field=models.CharField(default='1', max_length=5),
            preserve_default=False,
        ),
    ]
