# Generated by Django 3.2.6 on 2022-05-06 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0125_justificativaentrega_id_garagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificativaentrega',
            name='tipo_doc',
            field=models.CharField(default='57', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bipagempalete',
            name='filial',
            field=models.CharField(choices=[('1', 'SPO'), ('2', 'REC'), ('3', 'SSA'), ('4', 'FOR'), ('5', 'MCZ'), ('6', 'NAT'), ('7', 'JPA'), ('8', 'AJU'), ('9', 'VDC'), ('10', 'MG'), ('20', 'CTG'), ('21', 'TCO'), ('22', 'UDI'), ('23', 'TMA'), ('24', 'VIX'), ('30', 'BMA'), ('31', 'BPE'), ('32', 'BEL'), ('33', 'BPB'), ('34', 'SLZ'), ('35', 'BAL'), ('36', 'THE'), ('40', 'FMA')], max_length=3),
        ),
        migrations.AlterField(
            model_name='etiquetasdocumento',
            name='garagem',
            field=models.CharField(choices=[('1', 'SPO'), ('2', 'REC'), ('3', 'SSA'), ('4', 'FOR'), ('5', 'MCZ'), ('6', 'NAT'), ('7', 'JPA'), ('8', 'AJU'), ('9', 'VDC'), ('10', 'MG'), ('20', 'CTG'), ('21', 'TCO'), ('22', 'UDI'), ('23', 'TMA'), ('24', 'VIX'), ('30', 'BMA'), ('31', 'BPE'), ('32', 'BEL'), ('33', 'BPB'), ('34', 'SLZ'), ('35', 'BAL'), ('36', 'THE'), ('40', 'FMA')], max_length=3),
        ),
        migrations.AlterField(
            model_name='etiquetaspalete',
            name='filial',
            field=models.CharField(choices=[('1', 'SPO'), ('2', 'REC'), ('3', 'SSA'), ('4', 'FOR'), ('5', 'MCZ'), ('6', 'NAT'), ('7', 'JPA'), ('8', 'AJU'), ('9', 'VDC'), ('10', 'MG'), ('20', 'CTG'), ('21', 'TCO'), ('22', 'UDI'), ('23', 'TMA'), ('24', 'VIX'), ('30', 'BMA'), ('31', 'BPE'), ('32', 'BEL'), ('33', 'BPB'), ('34', 'SLZ'), ('35', 'BAL'), ('36', 'THE'), ('40', 'FMA')], max_length=3),
        ),
        migrations.CreateModel(
            name='OcorrenciaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=5)),
                ('filial', models.CharField(max_length=5)),
                ('garagem', models.CharField(max_length=5)),
                ('conhecimento', models.CharField(max_length=15)),
                ('tp_doc', models.CharField(max_length=5)),
                ('cod_ocor', models.CharField(max_length=5)),
                ('desc_ocor', models.CharField(max_length=200)),
                ('data_ocorrencia', models.DateField()),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portaria.justificativaentrega')),
            ],
        ),
    ]
