# Generated by Django 3.2.6 on 2022-05-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0126_auto_20220506_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcpj',
            name='aux_moradia',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
