# Generated by Django 3.2.6 on 2022-05-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0127_funcpj_aux_moradia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcpj',
            name='aux_moradia',
        ),
        migrations.AddField(
            model_name='nfservicopj',
            name='aux_moradia',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
