# Generated by Django 3.2.6 on 2022-05-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0129_auto_20220512_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificativaentrega',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
