# Generated by Django 3.2.6 on 2022-05-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0130_justificativaentrega_data_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='romxml',
            name='xmlfile',
            field=models.FileField(default='1', upload_to='xmls/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
