# Generated by Django 3.2.6 on 2022-05-23 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portaria', '0131_romxml_xmlfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacoesCompras',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nr_solic', models.CharField(max_length=10)),
                ('data', models.DateTimeField()),
                ('status', models.CharField(max_length=1)),
                ('filial', models.CharField(choices=[('1', 'SPO'), ('2', 'REC'), ('3', 'SSA'), ('4', 'FOR'), ('5', 'MCZ'), ('6', 'NAT'), ('7', 'JPA'), ('8', 'AJU'), ('9', 'VDC'), ('10', 'MG'), ('20', 'CTG'), ('21', 'TCO'), ('22', 'UDI'), ('23', 'TMA'), ('24', 'VIX'), ('30', 'BMA'), ('31', 'BPE'), ('32', 'BEL'), ('33', 'BPB'), ('34', 'SLZ'), ('35', 'BAL'), ('36', 'THE'), ('40', 'FMA')], max_length=3)),
                ('solicitante', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutosSolicitacoes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('produto', models.CharField(max_length=200)),
                ('qnt_itens', models.IntegerField()),
                ('solic_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.solicitacoescompras')),
            ],
        ),
    ]
