# Generated by Django 3.2.6 on 2022-05-26 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0135_auto_20220525_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacoesEntradas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('obs', models.TextField()),
                ('file1', models.FileField(upload_to='cpr/%Y/%m/%d')),
                ('file2', models.FileField(upload_to='cpr/%Y/%m/%d')),
                ('file3', models.FileField(upload_to='cpr/%Y/%m/%d')),
                ('cpr_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.solicitacoescompras')),
            ],
        ),
    ]
