# Generated by Django 3.2.6 on 2022-05-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0137_auto_20220526_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registraterceirizados',
            old_name='data',
            new_name='data_entrada',
        ),
        migrations.AddField(
            model_name='registraterceirizados',
            name='data_saida',
            field=models.DateTimeField(default='0001-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registraterceirizados',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/terceirizados/Y%-%m-%d'),
        ),
    ]
