# Generated by Django 3.2.6 on 2022-05-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0138_auto_20220527_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registraterceirizados',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
