# Generated by Django 3.2.6 on 2022-05-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0139_alter_registraterceirizados_data_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registraterceirizados',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/terceirizados/'),
        ),
    ]
