# Generated by Django 3.2.6 on 2022-06-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0141_alter_ticketchamado_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoescompras',
            name='email_solic',
            field=models.EmailField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
