# Generated by Django 3.2.6 on 2022-06-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0142_solicitacoescompras_email_solic'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificativaentrega',
            name='file',
            field=models.FileField(default=1, upload_to='justificativas/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
