# Generated by Django 3.2.6 on 2022-06-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0143_justificativaentrega_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoescompras',
            name='departamento',
            field=models.CharField(blank=True, choices=[('DIRETORIA', 'DIRETORIA'), ('FATURAMENTO', 'FATURAMENTO'), ('FINANCEIRO', 'FINANCEIRO'), ('RH', 'RH'), ('FISCAL', 'FISCAL'), ('MONITORAMENTO', 'MONITORAMENTO'), ('OPERACIONAL', 'OPERACIONAL'), ('FROTA', 'FROTA'), ('EXPEDICAO', 'EXPEDICAO'), ('COMERCIAL', 'COMERCIAL'), ('JURIDICO', 'JURIDICO'), ('DESENVOLVIMENTO', 'DESENVOLVIMENTO'), ('TI', 'TI'), ('FILIAIS', 'FILIAIS'), ('COMPRAS', 'COMPRAS')], max_length=15, null=True),
        ),
    ]
