# Generated by Django 3.2.6 on 2022-06-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0145_alter_ticketchamado_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificativaentrega',
            name='file',
            field=models.FileField(null=True, upload_to='justificativas/%Y/%m/%d'),
        ),
    ]
