# Generated by Django 3.2.6 on 2022-06-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0146_alter_justificativaentrega_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificativaentrega',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='justificativaentrega',
            name='confirmado_txt',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
