# Generated by Django 3.2.6 on 2022-06-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0147_auto_20220614_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugestoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('texto', models.TextField()),
                ('categoria', models.CharField(max_length=8)),
                ('file', models.FileField(blank=True, null=True, upload_to='sugestoes/%Y/%m/%d')),
                ('autor', models.CharField(default='anônimo', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='justificativaentrega',
            name='confirmado_txt',
        ),
    ]
