# Generated by Django 3.2.6 on 2022-06-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0148_auto_20220620_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoescompras',
            name='categoria',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
