# Generated by Django 3.2.6 on 2022-06-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0149_solicitacoescompras_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketchamado',
            name='servico',
            field=models.CharField(choices=[('DESCARGA', 'DESCARGA'), ('COMPROVANTE', 'COMPROVANTE'), ('PRAXIO', 'PRAXIO'), ('FISCAL', 'FISCAL')], max_length=15),
        ),
    ]
