# Generated by Django 3.2.6 on 2022-06-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0150_alter_ticketchamado_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoescompras',
            name='dt_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacoescompras',
            name='prazo_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
