# Generated by Django 3.2.6 on 2022-07-01 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0152_alter_solicitacoescompras_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solicitacoescompras',
            unique_together=set(),
        ),
    ]
