# Generated by Django 3.2.6 on 2022-07-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0153_alter_solicitacoescompras_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketchamado',
            name='categoria',
            field=models.CharField(blank=True, choices=[('FISCAL', (('CFOP', 'CFOP'), ('CANCELAR NFSe', 'CANCELAR NFSe'), ('CANCELAMENTO CTe', 'CANCELAMENTO CTe'), ('AVALIACAO CTe', 'AVALIACAO CTe')))], max_length=20, null=True),
        ),
    ]
