# Generated by Django 3.2.6 on 2022-07-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0154_ticketchamado_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailchamado',
            name='email_id',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
