# Generated by Django 3.2.6 on 2022-07-12 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0155_alter_emailchamado_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketchamado',
            name='ultima_att',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticketchamado',
            name='ultimo_autor',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacoescompras',
            name='categoria',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='solicitacoescompras',
            name='status',
            field=models.CharField(max_length=8),
        ),
    ]
