# Generated by Django 3.2.6 on 2022-07-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0156_auto_20220712_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketchamado',
            name='ultima_att',
            field=models.DateTimeField(),
        ),
    ]
