# Generated by Django 3.2.6 on 2022-07-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0157_alter_ticketchamado_ultima_att'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketchamado',
            name='ultima_att',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
