# Generated by Django 3.2.6 on 2022-07-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0158_alter_ticketchamado_ultima_att'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificativaentrega',
            name='recusa',
            field=models.BooleanField(default=False),
        ),
    ]
