# Generated by Django 3.2.6 on 2022-07-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0159_justificativaentrega_recusa'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoescompras',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='cpr/%Y/%m/%d'),
        ),
    ]
