# Generated by Django 3.2.6 on 2022-07-27 16:58

from django.db import migrations, models
import portaria.models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0161_auto_20220727_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demissoes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('empresa', models.IntegerField()),
                ('filial', models.IntegerField()),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[portaria.models.only_int])),
                ('dtadmissao', models.DateField()),
                ('dtdemissao', models.DateField(blank=True, null=True)),
                ('motivodemissao', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='solicitacoescompras',
            name='email_solic',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
