# Generated by Django 3.2.6 on 2022-07-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0162_auto_20220727_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demissoes',
            name='motivodemissao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
