# Generated by Django 3.2.6 on 2022-07-28 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portaria', '0163_alter_demissoes_motivodemissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueItens',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=100)),
                ('quantidade', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('tamanho', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='EstoqueSolicitacoes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filial', models.CharField(choices=[('1', 'SPO'), ('2', 'REC'), ('3', 'SSA'), ('4', 'FOR'), ('5', 'MCZ'), ('6', 'NAT'), ('7', 'JPA'), ('8', 'AJU'), ('9', 'VDC'), ('10', 'MG'), ('20', 'CTG'), ('21', 'TCO'), ('22', 'UDI'), ('23', 'TMA'), ('24', 'VIX'), ('30', 'BMA'), ('31', 'BPE'), ('32', 'BEL'), ('33', 'BPB'), ('34', 'SLZ'), ('35', 'BAL'), ('36', 'THE'), ('40', 'FMA')], max_length=3)),
                ('data_solic', models.DateField()),
                ('data_envio', models.DateField()),
                ('confirmacao', models.DateField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('autor_confirmacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_autor_confirmacao', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.estoqueitens')),
            ],
        ),
    ]
