# Generated by Django 3.2.6 on 2022-07-29 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portaria', '0164_estoqueitens_estoquesolicitacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoquesolicitacoes',
            name='autor_confirmacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estoque_autor_confirmacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estoquesolicitacoes',
            name='confirmacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estoquesolicitacoes',
            name='data_envio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
