# Generated by Django 3.2.6 on 2022-07-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0165_auto_20220729_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquesolicitacoes',
            name='quant_solic',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
