# Generated by Django 3.2.6 on 2022-08-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0166_estoquesolicitacoes_quant_solic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='desc',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
