# Generated by Django 3.2.6 on 2022-08-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0167_alter_estoqueitens_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='desc',
            field=models.CharField(max_length=100),
        ),
    ]
