# Generated by Django 3.2.6 on 2022-08-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0168_alter_estoqueitens_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='skurefxml',
            name='qnt_vol',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skurefxml',
            name='tp_vol',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
