# Generated by Django 3.2.6 on 2022-08-08 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portaria', '0170_auto_20220805_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtossolicitacoes',
            name='ultima_att',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacoescompras',
            name='ultima_att',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ultimaattcompras', to=settings.AUTH_USER_MODEL),
        ),
    ]
