# Generated by Django 3.2.6 on 2022-08-08 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portaria', '0171_auto_20220808_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtossolicitacoes',
            name='ultima_att',
        ),
        migrations.AddField(
            model_name='solicitacoesentradas',
            name='ultima_att',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
