# Generated by Django 3.2.6 on 2022-08-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0172_auto_20220808_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='kilometragem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='notas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketchamado',
            name='servico',
            field=models.CharField(choices=[('DESCARGA', 'DESCARGA'), ('COMPROVANTE', 'COMPROVANTE'), ('PRAXIO', 'PRAXIO'), ('FISCAL', 'FISCAL'), ('MARKETING', 'MARKETING')], max_length=15),
        ),
    ]
