# Generated by Django 3.2.6 on 2022-08-29 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0173_auto_20220824_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movpalete',
            name='palete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portaria.paletecontrol'),
        ),
    ]
