# Generated by Django 3.2.6 on 2022-09-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0175_auto_20220912_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoescompras',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
