# Generated by Django 3.2.6 on 2022-12-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0176_solicitacoescompras_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoescompras',
            name='pago',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
