# Generated by Django 3.2.6 on 2022-12-20 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portaria', '0177_solicitacoescompras_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailchamado',
            name='tkt_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.ticketchamado'),
        ),
        migrations.CreateModel(
            name='SolicMovPalete',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_ult_mov', models.DateField(default=django.utils.timezone.now)),
                ('origem', models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('MG', 'MG'), ('CTG', 'CTG'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('VIX', 'VIX')], max_length=3)),
                ('destino', models.CharField(choices=[('SPO', 'SPO'), ('REC', 'REC'), ('SSA', 'SSA'), ('FOR', 'FOR'), ('MCZ', 'MCZ'), ('NAT', 'NAT'), ('JPA', 'JPA'), ('AJU', 'AJU'), ('VDC', 'VDC'), ('MG', 'MG'), ('CTG', 'CTG'), ('TCO', 'TCO'), ('UDI', 'UDI'), ('TMA', 'TMA'), ('VIX', 'VIX')], max_length=3)),
                ('placa_veic', models.CharField(max_length=7)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('palete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portaria.paletecontrol')),
            ],
        ),
    ]
