# Generated by Django 3.2.6 on 2022-12-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0178_auto_20221220_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicmovpalete',
            old_name='data_ult_mov',
            new_name='data_solic',
        ),
        migrations.AddField(
            model_name='solicmovpalete',
            name='data_receb',
            field=models.DateField(blank=True, null=True),
        ),
    ]
