# Generated by Django 3.2.6 on 2022-12-20 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0179_auto_20221220_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicmovpalete',
            name='data_receb',
        ),
        migrations.AddField(
            model_name='solicmovpalete',
            name='solic_id',
            field=models.CharField(default='20221220120434SPOxxx111', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicmovpalete',
            name='data_solic',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
