# Generated by Django 3.2.6 on 2022-12-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0182_auto_20221227_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='desc',
            field=models.CharField(max_length=110),
        ),
    ]
