# Generated by Django 3.2.6 on 2022-12-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0184_auto_20221227_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='grupo',
            field=models.CharField(max_length=80),
        ),
    ]
