# Generated by Django 3.2.6 on 2022-12-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0185_alter_estoqueitens_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='grupo',
            field=models.CharField(max_length=100),
        ),
    ]
