# Generated by Django 3.2.6 on 2022-12-27 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0186_alter_estoqueitens_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='estoque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='portaria.estoqueitens'),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tamanhos', to='portaria.item'),
        ),
    ]
