# Generated by Django 3.2.6 on 2022-12-27 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0187_auto_20221227_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='estoque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portaria.estoqueitens'),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portaria.item'),
        ),
    ]
