# Generated by Django 3.2.6 on 2022-12-28 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0188_auto_20221227_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquesolicitacoes',
            name='tamanho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portaria.tamanho'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estoquesolicitacoes',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.item'),
        ),
    ]
