# Generated by Django 3.2.6 on 2022-12-28 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0189_auto_20221228_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoquesolicitacoes',
            name='item',
        ),
        migrations.RemoveField(
            model_name='estoquesolicitacoes',
            name='quant_solic',
        ),
        migrations.RemoveField(
            model_name='estoquesolicitacoes',
            name='tamanho',
        ),
        migrations.CreateModel(
            name='ItemCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField()),
                ('item', models.ManyToManyField(to='portaria.Tamanho')),
                ('solic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.estoquesolicitacoes')),
            ],
        ),
    ]
