# Generated by Django 3.2.6 on 2022-12-29 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0190_auto_20221228_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcart',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='item_C',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portaria.itemcart'),
        ),
        migrations.AlterField(
            model_name='item',
            name='estoque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portaria.estoqueitens'),
        ),
    ]
