# Generated by Django 3.2.6 on 2022-12-29 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0191_auto_20221229_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_C',
        ),
        migrations.AddField(
            model_name='tamanho',
            name='item_C',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portaria.itemcart'),
        ),
    ]
