# Generated by Django 3.2.6 on 2022-12-29 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0192_auto_20221229_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.estoquesolicitacoes')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
                ('tam', models.CharField(max_length=5)),
                ('qty', models.PositiveBigIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.cart')),
            ],
        ),
        migrations.RemoveField(
            model_name='tamanho',
            name='item_C',
        ),
        migrations.DeleteModel(
            name='ItemCart',
        ),
    ]
