# Generated by Django 3.2.6 on 2022-12-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0193_auto_20221229_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquesolicitacoes',
            name='colab',
            field=models.CharField(default='Gabriel Torres', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='validade',
            field=models.PositiveBigIntegerField(default=30),
            preserve_default=False,
        ),
    ]
