# Generated by Django 3.2.6 on 2022-12-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0194_auto_20221229_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
