# Generated by Django 3.2.6 on 2022-12-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0195_cartitem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='item',
            new_name='tam_id',
        ),
    ]
